// Emit the seed dataset as SQL.
// -----------------------------------------------------------------------------
//   npm run pg:seed:sql > seed.sql
//
// For a Postgres database you cannot reach with Prisma — no direct connection,
// or you would rather not put the password on a command line. Paste the output
// into the Supabase SQL editor (or psql) and it produces exactly what
// `npm run pg:seed` would have written.
//
// Same dataset module as the Prisma driver, so the two cannot diverge.

import { buildSeedData } from "../prisma/seed-data";
import { APP_SCHEMA } from "./app-schema";

function lit(value: unknown): string {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "number") return String(value);
  if (value instanceof Date) return `'${value.toISOString()}'`;
  // Postgres string literal: double any embedded single quotes.
  return `'${String(value).replace(/'/g, "''")}'`;
}

function insert<T extends object>(
  table: string,
  columns: (keyof T & string)[],
  rows: readonly T[]
): string {
  if (rows.length === 0) return "";
  const cols = columns.map((c) => `"${c}"`).join(", ");
  const values = rows
    .map((row) => {
      const record = row as Record<string, unknown>;
      return `  (${columns.map((c) => lit(record[c])).join(", ")})`;
    })
    .join(",\n");
  return `INSERT INTO "${APP_SCHEMA}"."${table}" (${cols}) VALUES\n${values};\n`;
}

/** AppSetting has a NOT NULL updatedAt with no default, so it is written explicitly. */
function insertSettings(rows: { key: string; value: string; label: string; description: string | null }[]): string {
  if (rows.length === 0) return "";
  const values = rows
    .map(
      (r) =>
        `  (${lit(r.key)}, ${lit(r.value)}, ${lit(r.label)}, ${lit(r.description)}, now())`
    )
    .join(",\n");
  return `INSERT INTO "${APP_SCHEMA}"."AppSetting" ("key", "value", "label", "description", "updatedAt") VALUES\n${values};\n`;
}

function main(): void {
  const d = buildSeedData();
  const q = (t: string) => `"${APP_SCHEMA}"."${t}"`;

  const out: string[] = [
    "-- Seed data for the Workload Allocation Tool.",
    "-- Generated by scripts/seed-to-sql.ts — do not edit by hand.",
    `-- Scoped entirely to the "${APP_SCHEMA}" schema; nothing else is touched.`,
    "",
    "BEGIN;",
    "",
    "-- Children before parents.",
    `DELETE FROM ${q("ActivityLog")};`,
    `DELETE FROM ${q("WorkSession")};`,
    `DELETE FROM ${q("AuditLog")};`,
    `DELETE FROM ${q("Assignment")};`,
    `DELETE FROM ${q("Ticket")};`,
    `DELETE FROM ${q("Shift")};`,
    `DELETE FROM ${q("Agent")};`,
    `DELETE FROM ${q("IngestionRule")};`,
    `DELETE FROM ${q("MailboxConfig")};`,
    `DELETE FROM ${q("SlaRule")};`,
    `DELETE FROM ${q("AppSetting")};`,
    "",
    insert("SlaRule", ["id", "ticketType", "slaMinutes", "businessHoursOnly", "active"], d.slaRules),
    insert("Agent", ["id", "adUpn", "displayName", "role", "concurrentCap", "active"], d.agents),
    insert("Shift", ["id", "agentId", "startsAt", "endsAt"], d.shifts),
    insert("MailboxConfig", ["id", "address", "platform", "active"], d.mailboxes),
    insert("IngestionRule", ["id", "mailboxId", "matchKind", "matchValue", "ticketType", "ruleOrder"], d.ingestionRules),
    insert(
      "Ticket",
      [
        "id", "source", "externalRef", "subject", "body", "ticketType",
        "receivedAt", "dueAt", "status", "currentAssigneeId", "onHoldSince",
        "holdAccumulatedMinutes", "holdReason", "resolvedAt", "closedAt", "updatedAt",
      ],
      d.tickets
    ),
    insert("Assignment", ["id", "ticketId", "agentId", "reason", "assignedAt", "unassignedAt"], d.assignments),
    insert("AuditLog", ["id", "ticketId", "actor", "event", "detailsJson", "at"], d.auditLogs),
    insertSettings(d.appSettings),
    insert("WorkSession", ["id", "agentId", "startedAt", "endedAt"], d.workSessions),
    insert("ActivityLog", ["id", "sessionId", "kind", "ticketId", "startedAt", "endedAt", "note"], d.activities),
    "COMMIT;",
  ];

  process.stdout.write(out.filter(Boolean).join("\n") + "\n");
}

main();
